version: '3'
services: 
  mongodb:
    image:  mongo:4.4.17-focal
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mariaf
      - MONGO_INITDB_ROOT_PASSWORD=mariaf
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mariaf
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mariaf
      - ME_CONFIG_MONGODB_SERVER=mongodb